export const amenityOptions = [
  "Free Wi-Fi",
  "High-Speed Internet",
  "Free Breakfast",
  "Restaurant",
  "Room Service",
  "Coffee Shop",
  "Bar",
  "Mini Bar",
  "Kitchen",
  "Kitchenette",
  "Refrigerator",
  "Microwave",
  "Electric Kettle",
  "Dining Area",
  "Air Conditioning",
  "Heating",
  "Ceiling Fan",
  "Smart TV",
  "Cable TV",
  "Streaming Services",
  "Work Desk",
  "Wardrobe",
  "Iron",
  "Hair Dryer",
  "Toiletries",
  "Hot Water",
  "Bathtub",
  "Private Bathroom",
  "Shared Bathroom",
  "Balcony",
  "Terrace",
  "Garden View",
  "City View",
  "Sea View",
  "Mountain View",
  "Swimming Pool",
  "Infinity Pool",
  "Children's Pool",
  "Gym",
  "Fitness Center",
  "Spa",
  "Sauna",
  "Steam Room",
  "Massage",
  "Jacuzzi",
  "Yoga Room",
  "Game Room",
  "Kids Play Area",
  "Children's Playground",
  "BBQ Area",
  "Picnic Area",
  "Fire Pit",
  "Private Beach",
  "Beach Access",
  "Water Sports",
  "Tennis Court",
  "Basketball Court",
  "Football Ground",
  "Golf Course",
  "Bicycle Rental",
  "Free Parking",
  "Valet Parking",
  "EV Charging Station",
  "Airport Shuttle",
  "Car Rental",
  "Bicycle Parking",
  "24-Hour Front Desk",
  "Express Check-in",
  "Express Check-out",
  "Concierge Service",
  "Luggage Storage",
  "Laundry",
  "Dry Cleaning",
  "Daily Housekeeping",
  "Wake-up Service",
  "Business Center",
  "Meeting Room",
  "Conference Hall",
  "Banquet Hall",
  "Wedding Venue",
  "Elevator",
  "Wheelchair Accessible",
  "Accessible Bathroom",
  "Smoke-Free Property",
  "Smoking Area",
  "Family Rooms",
  "Non-Smoking Rooms",
  "Pet Friendly",
  "Pet Area",
  "Generator Backup",
  "Power Backup",
  "Solar Power",
  "24-Hour Security",
  "CCTV",
  "Security Guard",
  "Key Card Access",
  "Fire Extinguisher",
  "Smoke Detector",
  "First Aid Kit",
  "Safe Deposit Box",
  "Locker",
  "ATM",
  "Currency Exchange",
  "Convenience Store",
  "Gift Shop",
  "Vending Machine",
  "Library",
  "Co-working Space",
  "Study Room",
  "Prayer Room",
  "Event Space",
  "Rooftop Lounge",
  "Outdoor Seating",
  "Private Entrance",
  "Self Check-in",
  "Furnished",
  "Washing Machine",
  "Clothes Dryer",
  "Dishwasher",
  "Baby Crib",
  "Extra Bed Available",
  "Soundproof Rooms",
  "Blackout Curtains",
  "Digital Door Lock",
] as const;

export function parseAmenityList(value: string | undefined) {
  return (value ?? "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

export function serializeAmenityList(values: string[]) {
  return values.join(", ");
}

export function getAmenityOptions(extraAmenities: string[] = []) {
  return Array.from(new Set([...amenityOptions, ...extraAmenities]));
}
